### PR TITLE
material theme :owo:

### PR DESCRIPTION
**Pull request by HiItsDevin**

### CODE REVIEW

**Comment by JackDotJS** [comment]
screenshot provided over discord: 

image

**Comment by JackDotJS** [comment]
question: what's the size difference of the final build between this version and the current version with the regular theme?

**Comment by HiItsDevin** [comment]
uhhh this is as of right now, so i think a whole 5mb difference.. which is ouch.
image

**Comment by JackDotJS** [comment]
it's more of a ~3.2 MB difference, since the current build is ~2.4 MB. but still, that means adding this theme more than doubles the size of the app. i would much prefer to keep this app as small as possible, and doubling the size just for a fancier UI *really* does not sit well with me. if it was for something functional (like native file browsing dialogs) then maybe, but this is purely cosmetic, so unfortunately i'm gonna have to turn this down.

**Pull request closed without merging**
